/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MainLambda": {
      "name": string
      "type": "sst.aws.Function"
    }
    "whatsapp-bot-dev-campaign": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "whatsapp-bot-dev-flow": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "whatsapp-bot-dev-user": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}