/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    ApiGateway: {
      type: "sst.aws.ApiGatewayV2";
      url: string;
    };
    DynoUser: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    MainLambda: {
      name: string;
      type: "sst.aws.Function";
    };
    S3Bucket: {
      name: string;
      type: "sst.aws.Bucket";
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
